# This is a basic workflow to help you get started with Actions

name: Build_And_Test

on:
  pull_request:
    branches:
      - main
      - PreProd

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # - name: Test
    #   run: dotnet Test --configuration Release --no-restore

