# This is a basic workflow to help you get started with Actions

name: HotFixDeploy

on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    if: "contains(github.event.head_commit.message, '*FIX*')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # - name: Test
    #   run: dotnet Test --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --no-build --output Publish --configuration Release


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-qrlz --delete"
          SOURCE: "Publish/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}prod/
          SCRIPT_BEFORE: appservice stop arkenstone_api
          SCRIPT_AFTER: appservice start arkenstone_api
